--CREATE DATABASE RedStore;

--USE RedStore;

CREATE TABLE Category (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL
);

CREATE TABLE [Product] (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Image] NVARCHAR(MAX) NOT NULL,
	Price MONEY NOT NULL,
	[Description] NTEXT NOT NULL,
	CategoryID INT,
	CONSTRAINT FK_CategoryProduct FOREIGN KEY (CategoryID) 
	REFERENCES Category(ID)
);

CREATE TABLE Account (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[User] VARCHAR(255) UNIQUE NOT NULL,
	[Password] VARCHAR(255) NOT NULL,
	[Role] TINYINT NOT NULL
);

--DROP TABLE Cart;

CREATE TABLE Cart (
	UserID INT, 
	ProductID INT,
	Size TINYINT NOT NULL,
	Color INT NOT NULL,
	Quantity INT NOT NULL,
	CONSTRAINT PK_Cart PRIMARY KEY (UserID),
	CONSTRAINT FK_UserCart FOREIGN KEY (UserID) REFERENCES Account(ID),
	CONSTRAINT FK_CartProduct FOREIGN KEY (ProductID) REFERENCES [Product](ID)
);

CREATE TABLE Size (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
);

CREATE TABLE ProductSize (
	ProductID INT,
	SizeID INT,
	CONSTRAINT PK_ProductSize PRIMARY KEY (ProductID, SizeID),
	CONSTRAINT FK_ProductSize FOREIGN KEY (ProductID) REFERENCES [Product](ID),
	CONSTRAINT FK_SizeProduct FOREIGN KEY (SizeID) REFERENCES Size(ID)
);

CREATE TABLE Color (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
);

CREATE TABLE ProductColor (
	ProductID INT,
	ColorID INT,
	CONSTRAINT PK_ProductColor PRIMARY KEY (ProductID, ColorID),
	CONSTRAINT FK_ProductColor FOREIGN KEY (ProductID) REFERENCES [Product](ID),
	CONSTRAINT FK_ColorProduct FOREIGN KEY (ColorID) REFERENCES Color(ID)
);

CREATE TABLE [Image] (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	ProductID INT,
	Link NVARCHAR(MAX) NOT NULL,
	CONSTRAINT FK_ProductImage FOREIGN KEY (ProductID) REFERENCES [Product](ID)
);